<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Producto;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $electronica = Categoria::where('nombre', 'Electrónica')->first();
        $ropa = Categoria::where('nombre', 'Ropa')->first();
        $hogar = Categoria::where('nombre', 'Hogar')->first();
        $deportes = Categoria::where('nombre', 'Deportes')->first();
        $libros = Categoria::where('nombre', 'Libros')->first();

        Producto::insert([
            [
                'nombre' => 'Laptop Lenovo IdeaPad',
                'descripcion' => 'Laptop Intel Core i5, 8GB RAM, 512GB SSD',
                'precio_venta_actual' => 4500.00,
                'imagen' => 'productos/laptop-lenovo.jpg',
                'estado' => true,
                'categoria_id' => $electronica->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Smartphone Samsung Galaxy',
                'descripcion' => 'Teléfono inteligente Android',
                'precio_venta_actual' => 2800.00,
                'imagen' => 'productos/samsung-galaxy.jpg',
                'estado' => true,
                'categoria_id' => $electronica->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Polera Deportiva',
                'descripcion' => 'Polera de algodón unisex',
                'precio_venta_actual' => 120.00,
                'imagen' => 'productos/polera.jpg',
                'estado' => true,
                'categoria_id' => $ropa->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Silla de Oficina',
                'descripcion' => 'Silla ergonómica con soporte lumbar',
                'precio_venta_actual' => 850.00,
                'imagen' => 'productos/silla.jpg',
                'estado' => true,
                'categoria_id' => $hogar->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Balón de Fútbol',
                'descripcion' => 'Balón profesional tamaño 5',
                'precio_venta_actual' => 180.00,
                'imagen' => 'productos/balon.jpg',
                'estado' => true,
                'categoria_id' => $deportes->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Laravel para Principiantes',
                'descripcion' => 'Guía práctica de Laravel 12',
                'precio_venta_actual' => 95.00,
                'imagen' => 'productos/laravel.jpg',
                'estado' => true,
                'categoria_id' => $libros->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Laptop Lenovo IdeaPad',
                'descripcion' => 'Laptop Intel Core i5, 8GB RAM, SSD 512GB',
                'precio_venta_actual' => 4500,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $electronica->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Laptop HP 15',
                'descripcion' => 'Laptop Intel Core i7, 16GB RAM',
                'precio_venta_actual' => 6200,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $electronica->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Monitor Samsung 24"',
                'descripcion' => 'Monitor Full HD',
                'precio_venta_actual' => 1200,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $electronica->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Teclado Mecánico RGB',
                'descripcion' => 'Teclado gamer',
                'precio_venta_actual' => 350,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $electronica->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mouse Inalámbrico Logitech',
                'descripcion' => 'Mouse ergonómico',
                'precio_venta_actual' => 180,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $electronica->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ropa
            [
                'nombre' => 'Polera Básica Blanca',
                'descripcion' => 'Algodón 100%',
                'precio_venta_actual' => 60,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $ropa->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Jeans Azul Clásico',
                'descripcion' => 'Denim resistente',
                'precio_venta_actual' => 180,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $ropa->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Chaqueta Deportiva',
                'descripcion' => 'Impermeable',
                'precio_venta_actual' => 250,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $ropa->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Gorra Negra',
                'descripcion' => 'Ajustable',
                'precio_venta_actual' => 45,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $ropa->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Sudadera Gris',
                'descripcion' => 'Con capucha',
                'precio_venta_actual' => 140,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $ropa->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hogar
            [
                'nombre' => 'Silla de Oficina',
                'descripcion' => 'Ergonómica',
                'precio_venta_actual' => 850,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $hogar->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Escritorio Ejecutivo',
                'descripcion' => 'Melamina premium',
                'precio_venta_actual' => 1200,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $hogar->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Lámpara LED',
                'descripcion' => 'Bajo consumo',
                'precio_venta_actual' => 90,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $hogar->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ventilador de Pie',
                'descripcion' => '3 velocidades',
                'precio_venta_actual' => 320,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $hogar->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Juego de Ollas',
                'descripcion' => 'Acero inoxidable',
                'precio_venta_actual' => 450,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $hogar->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Deportes
            [
                'nombre' => 'Balón de Fútbol',
                'descripcion' => 'Tamaño oficial',
                'precio_venta_actual' => 180,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $deportes->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Balón de Básquet',
                'descripcion' => 'Uso profesional',
                'precio_venta_actual' => 200,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $deportes->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mancuernas 10kg',
                'descripcion' => 'Par de mancuernas',
                'precio_venta_actual' => 300,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $deportes->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cuerda para Saltar',
                'descripcion' => 'Ajustable',
                'precio_venta_actual' => 35,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $deportes->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Guantes de Boxeo',
                'descripcion' => '12 oz',
                'precio_venta_actual' => 220,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $deportes->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Libros
            [
                'nombre' => 'Laravel 12 Desde Cero',
                'descripcion' => 'Desarrollo web moderno',
                'precio_venta_actual' => 120,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $libros->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'PHP Profesional',
                'descripcion' => 'Buenas prácticas',
                'precio_venta_actual' => 110,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $libros->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Bases de Datos SQL',
                'descripcion' => 'Diseño y optimización',
                'precio_venta_actual' => 95,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $libros->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Clean Code',
                'descripcion' => 'Código limpio y mantenible',
                'precio_venta_actual' => 150,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $libros->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Patrones de Diseño',
                'descripcion' => 'Soluciones reutilizables',
                'precio_venta_actual' => 180,
                'imagen' => null,
                'estado' => true,
                'categoria_id' => $libros->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
