### Listar categorías
GET http://127.0.0.1:8000/api/categoria
Authorization: Bearer 1|WbkmdXzP4FiMf7JN87JwVevMIWFdIMuUEBlxLG7b8354c24e
Accept: application/json

###

### Guardar categoría
POST http://127.0.0.1:8000/api/categoria
Authorization: Bearer 1|WbkmdXzP4FiMf7JN87JwVevMIWFdIMuUEBlxLG7b8354c24e
Content-Type: application/json

{
    "nombre": "GASEOSAS",
    "descripcion": "Productos"
}

###

### Mostrar una categoría
GET http://127.0.0.1:8000/api/categoria/1
Authorization: Bearer 1|EtN9a0w0B7xP1u8ZSFBuC30mzonv5CTu1LeqTltMb251b46f
Accept: application/json

###

### Modificar categoría
PUT http://127.0.0.1:8000/api/categoria/1
Authorization: Bearer 1|EtN9a0w0B7xP1u8ZSFBuC30mzonv5CTu1LeqTltMb251b46f
Content-Type: application/json

{
    "nombre": "Electrónica y Tecnología",
    "descripcion": "Productos tecnológicos y electrónicos"
}

###

### Eliminar categoría
DELETE http://127.0.0.1:8000/api/categoria/1
Authorization: Bearer 1|EtN9a0w0B7xP1u8ZSFBuC30mzonv5CTu1LeqTltMb251b46f
Accept: application/json