###
GET http://127.0.0.1:8000/api/nota?tipo_nota=venta
Accept: application/json
Authorization: Bearer 1|qTomhcpJlIN6XcelzFIFgOBWOExAxsuKU0Ip1mJk59a0b1e4

### NOTA COMPRA
POST http://127.0.0.1:8000/api/nota
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|qTomhcpJlIN6XcelzFIFgOBWOExAxsuKU0Ip1mJk59a0b1e4

{
    "tipo_nota": "compra",
    "observaciones": "NINGUNO",
    "clienteproveedor_id": 1,
    "movimientos": [
        { "almacen_id": 1, "producto_id": 31, "cantidad": 20, "tipo_movimiento": "ingreso", "precio_compra": 198.98, "precio_venta": 0.00, "observaciones": "SIN OBSERVACIONES" },
        { "almacen_id": 1, "producto_id": 30, "cantidad": 50, "tipo_movimiento": "ingreso", "precio_compra": 98.98, "precio_venta": 0.00, "observaciones": "NINGUNO" }
    ]
}

### NOTA VENTA

POST http://127.0.0.1:8000/api/nota
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|qTomhcpJlIN6XcelzFIFgOBWOExAxsuKU0Ip1mJk59a0b1e4

{
    "tipo_nota": "venta",
    "observaciones": "NINGUNO",
    "clienteproveedor_id": 2,
    "movimientos": [
        { "almacen_id": 1, "producto_id": 31, "cantidad": 15, "tipo_movimiento": "salida", "precio_compra": 0.00, "precio_venta": 250.00, "observaciones": "NINGUNO" }
    ]
}

### Nota
GET http://127.0.0.1:8000/api/nota/1/exportar-nota
Authorization: Bearer 1|qTomhcpJlIN6XcelzFIFgOBWOExAxsuKU0Ip1mJk59a0b1e4
