GET http://127.0.0.1:8000/api/role
Authorization: Bearer 2|4M6PPePehzIoKUVsgNGUHKhCQkysMVYJsQmtp5f5d005adbf


###
POST http://127.0.0.1:8000/api/role
Content-Type: application/json
Authorization: Bearer 2|4M6PPePehzIoKUVsgNGUHKhCQkysMVYJsQmtp5f5d005adbf

{
    "nombre": "DIRECTOR"
}

### Modificar
PUT http://127.0.0.1:8000/api/role/2
Content-Type: application/json
Authorization: Bearer 2|4M6PPePehzIoKUVsgNGUHKhCQkysMVYJsQmtp5f5d005adbf

{
    "nombre": "GERENTE",
    "detalle": "Administrador"
}

### Asignar permiso
POST http://127.0.0.1:8000/api/role/2/asignar_permiso
Authorization: Bearer 2|4M6PPePehzIoKUVsgNGUHKhCQkysMVYJsQmtp5f5d005adbf
Content-Type: application/json

{
    "permisos": [2]
}
