GET http://127.0.0.1:8000/api/usuario
Authorization: Bearer 2|4M6PPePehzIoKUVsgNGUHKhCQkysMVYJsQmtp5f5d005adbf
Accept: application/json

### Guardar
POST http://127.0.0.1:8000/api/usuario
Authorization: Bearer 1|hr8Z9et5pbSR9QyN7PLJEuTOA5q1OIJpSgv4pegdff4ea24a
Content-Type: application/json

{
    "name": "david",
    "email": "david@mail.com",
    "password": "david54321"
}

### mostrar
GET http://127.0.0.1:8000/api/usuario/2
Authorization: Bearer 1|hr8Z9et5pbSR9QyN7PLJEuTOA5q1OIJpSgv4pegdff4ea24a


### modificar
PUT http://127.0.0.1:8000/api/usuario/2
Authorization: Bearer 1|hr8Z9et5pbSR9QyN7PLJEuTOA5q1OIJpSgv4pegdff4ea24a
Content-Type: application/json

{
  "name": "david",
  "email": "david@mail.com"
}

### eliminar
DELETE http://127.0.0.1:8000/api/usuario/3
Authorization: Bearer 6|590fA3hncqTOunlvwnOF2W3zc6v0Nt4odVQeRRXt8bc4c554

### Asignar role
POST http://127.0.0.1:8000/api/usuario/1/asignar_role
Authorization: Bearer 1|hr8Z9et5pbSR9QyN7PLJEuTOA5q1OIJpSgv4pegdff4ea24a
Content-Type: application/json

{
  "role": "GERENTE"
}

### quitar Role
POST http://127.0.0.1:8000/api/usuario/1/quitar_role
Authorization: Bearer 2|4M6PPePehzIoKUVsgNGUHKhCQkysMVYJsQmtp5f5d005adbf
Content-Type: application/json

{
  "role": "ADMIN"
}
